### PR TITLE
Tool initialization on Windows

### PR DESCRIPTION
**Pull request by hansangbae**
This change enables tool initialization on Windows.
The master branch was also merged to fix some build issues on Windows.
I believe Issues #3 and #27 are addressed here, but let me know if there is something to be improved.

### CODE REVIEW

**Comment by hansangbae** [comment]
Fix for the regression in 376.kdtree was committed.

**Comment by jprotze** [comment]
Everything, but removing the weak attribute seems to work. (all OMPT tests fail in my environment)
I will accept the PR and then swap the order of #ifs for the weak attribute.

**Comment by jprotze** [comment]
With 58d1570 I can LD_PRELOAD an openMP runtime library and still activate a tool built into the application (as we do with callback.h for the tests). Before that change, the tool loading failed with preloaded runtime.

**Comment by jmellorcrummey** [comment]
The version of ompt_start_tool provided by Intel won't execute the print protected by OMPT_DEBUG if KMP_DYNAMIC_LIB is set. I see no reason why it shouldn't alway execute the print if OMPT_DEBUG  is set and ret == NULL

**Pull request merged**
